server:
  port: ${PORT:5001}

spring:
  data:
    mongodb:
      uri: mongodb+srv://kaif6388:KAIFkhan6388@cluster0.rxnir.mongodb.net/ai-job-accessibility?retryWrites=true&w=majority&appName=Cluster0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    secret: Kaifkhan638891@&
  gemini:
    api-key: ${GEMINI_API_KEY:AIzaSyClsioS040Ydo1xE35FHvssQbN24CNr9f8}
  env: ${SPRING_PROFILES_ACTIVE:development}

logging:
  level:
    com.ai.accessibility: DEBUG
    org.springframework.web: INFO
